compute_environment: LOCAL_MACHINE
debug: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
mixed_precision: 'no'  # Set to 'no' because bf16 is typically for GPU
enable_cpu_affinity: true  # Enable CPU affinity
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: true  # Use CPU
